list = []

cell_organism_bool = []
cyst_formation = []
size = []
core_alability = []
presence_of_pseudomurein = []
eterna_growth = []
chlorophyll_percentage = []
number_of_cells = []

Bacteria = []
Archaea = []
Protista = []
Chromista = []
Plants = []
Animals = []
Fungi = []
Viruses = []
